server:
  port: 8100
eureka:
  client:
    service-url:
      defaulZone: 'http://localhost:8761/'
resilience4j:
  bulkhead:
    instances:
      foo-bar:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      foo-bar:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin0123
  jackson:
    default-property-inclusion: non-null
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    user: root
    password: admin0123
  sleuth:
    sampler:
      probability: 1.0
springdoc:
  api-docs:
    path: book-service/v3/api-docs